### ISSUE TITLE
One question

### ISSUE THREAD

**Issue by wudiduojimone** [edward3862/LoFGAN-pytorch#10]
Thangks for your great work. I have some question due to my poor GPU with only 8GB memory when I try to reproduce your work. And I want to change some parameter of LOFGAN to make it suitable for the picture with a size of 32*32*3. Do you think  it is feasible? and can you give me some advice on how to change the parameter?

**Comment by edward3862** [comment]
Hi, @wudiduojimone. For input size 128*128*3, the local fusion module is operated with feature map size 8*8, which means the image size is down-sampled four times. For input size 32*32*3, it will be operated at size 2*2, which may not be so 'local' anymore, so you may need to reduce the number of layers of the encoder and decoder, but I'm not sure which parameter is better. For the problem of GPU memory, you can try to remove the gradient penalty.

**Comment by wudiduojimone** [comment]
师姐，这是不是就是说如果要处理的图像大小为`32*32*3`，encoder里的层数设置为2层，那么得到的LFM模块的输入就是`8*8`的张量，就会“local”了。对`于64*64*3`的图像，encoder里的层数设置为3层那么得到的LFM的输入就是`8*8`的。师姐，我这个理解是对的吗？另外就是假如输入的图像是单通道的图像（灰度图），网络结构需要怎么修改吗

**Comment by edward3862** [comment]
Yes. You can just reduce the number of down-sampling operations instead of removing the entire layer. I think how to choose the resolution of LFM depends on the characteristics of the input image, different attempts are recommended. For a grayscale image, you may modify the convolution parameter of the first encoder layer and the last decoder layer.

**Comment by wudiduojimone** [comment]
Thanks for your reply. I will try. In the same time, I have a new question,that's why does LOFGAN'generator have good performance than other method based on GAN(especially like WGAN and some other classical GAN)  on limited datasets? I read the paper,but I only find the comparation between LOFGAN and other few shot'GAN.Can you help me figure out  the question'answer?
