### ISSUE TITLE
about "classification" of Discriminator

### ISSUE THREAD

**Issue by day2nightya** [edward3862/LoFGAN-pytorch#11]
Hi, Edward.
Thanks a lot for your excellent work.
I met this problem when I study your paper and code.That's I don't understand what's the purpose of  "classification" layer in Discriminator. So I want to ask for your opinion.

**Comment by edward3862** [comment]
Hi, @day2nightya.
The classification layer is used to predict the category of images in the current task. Reference code can be found here: https://github.com/NVlabs/FUNIT/blob/198f430b6ef1abe940251b30f51d5cc68a476787/networks.py#L66
