### ISSUE TITLE
Questions regarding Animal Faces dataset.

### ISSUE THREAD

**Issue by ankanbhunia** [edward3862/LoFGAN-pytorch#12]
Thanks for the exellent work. I have a query reagarding the dataset used in this paper. The shared .npy file for the Animal Faces dataset has a dimension of (149, 100, 128, 128, 3). It means 100 images for each class. The same is also mentioned in the paper. Thus, total it has 14900 images. However, the orginal Animal Faces dataset proposed in the FUNIT paper [1] has 117574 images, (~750 images per class). I am wondering why this paper doesn't use the whole set. Are the 100 images sampled randomly from the original set?

In the Flower dataset .npy file also there are reduced number of samples than the original dataset. 

[1] Few-Shot Unsupervised Image-to-Image Translation

**Comment by edward3862** [comment]
Hi, @ankanbhunia.
Yes, we use the same setting as the MatchingGAN paper: 
> For these categories, we randomly choose 100 images from each category to ﬁt a low-data setting.

**Comment by ankanbhunia** [comment]
@edward3862 Thanks for your reply.
