### ISSUE TITLE
关于相似度函数g是如何计算的？

### ISSUE THREAD

**Issue by 516396859** [edward3862/LoFGAN-pytorch#14]
作者您好，请问下，文中的相似度函数g具体是？在代码中，我看到的只是一个均匀分布替代相似度计算。希望解答一下，祝科研顺利！

**Comment by edward3862** [comment]
你好，g用的是余弦相似度。

> We use cosine similarity as the similarity function g in Eq.1

**Comment by edward3862** [comment]
https://github.com/edward3862/LoFGAN-pytorch/blob/ed6c4a8ff8b29953bbd0881a48a962c5b5959ea3/networks/lofgan.py#L292

**Comment by 516396859** [comment]
Thank you very much for your work. I wish you every success in your work.
