### ISSUE TITLE
关于论文中Figure 4和Figure 5

### ISSUE THREAD

**Issue by ecnuljzhang** [edward3862/LoFGAN-pytorch#16]
请问作者，论文中Figure 4是怎么得到的，有代码可以参考一下吗？Figure 5对于不同的η，是重新训练一次还是只在测试的时候改变η的值呢？

**Comment by edward3862** [comment]
您好，Figure 4请参考 ``main_vis_sim.py``，Figure 5是针对不同的η重新训练的。

**Comment by ecnuljzhang** [comment]
了解了，非常感谢！

Zheng Gu ***@***.***> 于2022年8月4日周四 19:55写道：
