### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by mschr1s** [edward3862/LoFGAN-pytorch#25]
Hi,I could not find the dataset vgg_face_data_rgb.npy,the link is not exist. Could you share it again?

**Comment by edward3862** [comment]
Hi, previously I used the dataset link from https://github.com/bcmi/Awesome-Few-Shot-Image-Generation, but it seems this dataset link is not right currently:( I'll try to look for it on my previous server, but cannot guarantee being able to find it and might take some time. 

If you find it in somewhere else, please also feel free to tell me. Thank you!

**Comment by edward3862** [comment]
Hi, I have found the dataset and upload it in a new link in README:)
