### ISSUE TITLE
How to reproduce the FID indicator?

### ISSUE THREAD

**Issue by VIROBO-15** [edward3862/LoFGAN-pytorch#4]
Thank you for your good job! I have a question about the FID. 
python main_metric.py --gpu 0 --dataset flower --name results/flower_lofgan --real_dir **datasets/for_fid/flower** --ckpt gen_00100000.pt  --fake_dir test_for_fid

Can you please let me know where is **"datasets/for_fid/flower"** present to calculate the fid score.

**Comment by edward3862** [comment]
Hi there, the real images will be sampled from the dataset and saved in `real_dir`. You can find the corresponding code in `main_metric.py`.

**Comment by VIROBO-15** [comment]
Thank you Gu for your response. I used the code to calculate the LPIPS distance. However, I failed to reproduce the actual LPIPS distance. Would you share your experimental settings?  
My calculated LPIPS on flower dataset is 0.3779 and in reported number in the paper is 0.3862

Can you please help me out in this

**Comment by edward3862** [comment]
Hello, I update the evaluation code, could you please try again?

**Comment by VIROBO-15** [comment]
Hi, I performed evaluation again but it's 0.374 this time far from the actual number which is 0.3862.
And for animal dataset the FID score is very high that is 664.93 but in the paper it's reported as 112.81.
Can you please help me in this

**Comment by edward3862** [comment]
That's weird... Could you show me the script you run?

**Comment by edward3862** [comment]
As for the FID, I ran the code several times with different random seeds and got an average result of about 0.3877. Did you use the pre-trained model or a new re-trained one?

**Comment by VIROBO-15** [comment]
python main_metric.py --gpu 0 --dataset flower --name results/flower_lofgan --real_dir datasets/for_fid/flower --ckpt gen_00100000.pt --fake_dir test_for_fid

I am using this and i have used pretrained-model

**Comment by VIROBO-15** [comment]
![Screenshot from 2021-12-29 23-46-12](https://user-images.githubusercontent.com/56671968/147698200-bf2df4e7-8175-4a59-a12f-0fc140f30c15.png)

**Comment by edward3862** [comment]
For the issue of Flower, I think it is normal to have some differences on different devices. Can you try some more times?
For animals, there seems to be something wrong here. Can you show the output of running the command?

**Comment by VIROBO-15** [comment]
![Screenshot from 2021-12-30 10-36-33](https://user-images.githubusercontent.com/56671968/147727715-7f87f41a-4802-4ea7-8674-3638397c8b7c.png)
Can you have the look of this

**Comment by edward3862** [comment]
How many images are in your `fake_dir` folder?

**Comment by VIROBO-15** [comment]
fake_dir has 201150 animal images

**Comment by edward3862** [comment]
There shouldn't be so many images. Can you check the shape of `data`, `data_for_gen`, and `data_for_fid`? And what are the filenames in your `fake_dir`?

**Comment by VIROBO-15** [comment]
data = (2235, 100, 64, 64, 3) 
data_for_fid = (2235, 90, 64, 64, 3) 
data_for_gen = (2235, 10, 64, 64, 3)

fake_dir = 2_047.png this is filename format

**Comment by edward3862** [comment]
I think that's not the animal dataset. The data shape of animal should be (149*100*128*128*3). Can you check if the images in your `real_dir` are actually animal face images?

**Comment by VIROBO-15** [comment]
Can you please tell the size vggface data set

**Comment by VIROBO-15** [comment]
Thank you @edward3862 very much there was a minor issue which is resolved. 
Thank you for the great work.
Thank you for the help

**Comment by jiaoxue52** [comment]
>Hello, VIROBO-15，sorry to bother you, I was able to complete the decompression of the npy file after downloading the datasets of this code reproduction, I don't know if you can share your decompression code? Once again sorry for my interruption and look forward to your reply, thank you.

**Comment by VIROBO-15** [comment]
The author have already provided the .npy files

**Comment by jiaoxue52** [comment]
> The author have already provided the .npy files
Hello, thanks for your reply, I saw the note given by the author: Download the [datasets] and unzip them in datasets folder. There is a decompression requirement, so I try to extract the downloaded npy, did you not perform the decompression step? Thank you again for your reply.
