### ISSUE TITLE
How to realize Visualization of the Learned Similarity

### ISSUE THREAD

**Issue by sdnulwk** [edward3862/LoFGAN-pytorch#5]
Hi, Edward～Thank you for your excellent work！
In section 4.2 of your paper, this part of the work is really interesting. 
I have two problems: (1) Is this subsection of the experiment implemented with grad-cam? (2) Can you share the relevant code? This trick for the highlight is very clever.

Happy New Year to you! Good work in the new year!

**Comment by edward3862** [comment]
Hi there and thank you~ It is not implemented by grad-cam. We get the similarity map just as we do in the LFM. The code is uploaded in `main_vis_sim.py`.

**Comment by sdnulwk** [comment]
Thank you for the great work!
Thank you for the help😄
