### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by Patricia886** [edward3862/LoFGAN-pytorch#8]
Hi, Edward. Thanks for your excellent work. I could not find the dataset vgg_face_data_rgb.npy.Could you share it? THX!

**Comment by edward3862** [comment]
Hi, the link is here.
https://drive.google.com/file/d/1oLLIyajt_CIT9SgQ5fZPX-Ple45xLeuU/view?usp=sharing

**Comment by Patricia886** [comment]
Thanks! But could you provide the original data instead of the .npy file?

**Comment by edward3862** [comment]
The .npy file is downloaded from the MatchingGAN repo, maybe you can find the original data here.
https://drive.google.com/drive/folders/15x2C11OrNeKLMzBDHrv8NPOwyre6H3O5

**Comment by Patricia886** [comment]
Thank you very much!!!
